In [26]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [27]:
# df.describe(include='all').style.background_gradient(cmap='coolwarm')

In [28]:
data = pd.read_csv(r"C:\Users\mk744\Downloads\customer (1).csv").drop(columns=['age', 'gender'])
data.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [29]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(data.iloc[:, 0:2], data.iloc[:, -1], test_size= 0.2)
ord_enc = OrdinalEncoder(categories= [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
X_train = ord_enc.fit_transform(X_train)
X_test = ord_enc.transform(X_test)

In [30]:
X_train, X_test

(array([[1., 0.],
        [0., 0.],
        [1., 2.],
        [2., 0.],
        [0., 0.],
        [1., 1.],
        [0., 2.],
        [1., 2.],
        [2., 2.],
        [0., 2.],
        [0., 2.],
        [0., 0.],
        [0., 2.],
        [0., 0.],
        [2., 2.],
        [1., 0.],
        [2., 0.],
        [2., 1.],
        [1., 1.],
        [2., 2.],
        [0., 2.],
        [0., 2.],
        [2., 0.],
        [2., 0.],
        [2., 1.],
        [2., 0.],
        [2., 0.],
        [2., 1.],
        [0., 1.],
        [2., 2.],
        [0., 2.],
        [1., 1.],
        [0., 1.],
        [2., 2.],
        [1., 1.],
        [0., 1.],
        [0., 1.],
        [1., 1.],
        [0., 2.],
        [1., 0.]]),
 array([[0., 2.],
        [1., 1.],
        [2., 1.],
        [1., 0.],
        [1., 2.],
        [0., 0.],
        [2., 1.],
        [2., 1.],
        [1., 0.],
        [2., 2.]]))

In [31]:
ord_enc.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [32]:
ord_enc.feature_names_in_

array(['review', 'education'], dtype=object)

In [33]:
ord_enc.n_features_in_

2

In [34]:
Dataset = pd.read_csv(r"C:\Users\mk744\OneDrive - Poornima University\Desktop\cropdata_updated.csv").drop(columns=['MOI', 'temp', 'humidity', 'result'])
Dataset.head()

crop ID   soil_type Seedling Stage
0   Wheat  Black Soil    Germination
1   Wheat  Black Soil    Germination
2   Wheat  Black Soil    Germination
3   Wheat  Black Soil    Germination
4   Wheat  Black Soil    Germination

In [35]:
# Select columns
X = Dataset[['crop ID', 'soil_type']]
y = Dataset['Seedling Stage']

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)
enc = OrdinalEncoder(categories= [['Wheat', 'Chilli', 'Potato', 'Carrot', 'Tomato'], 
                                  ['Clay Soil', 'Sandy Soil', 'Red Soil', 'Loam Soil',
                                   'Black Soil', 'Alluvial Soil', 'Chalky Soil']])

In [37]:
X_train = enc.fit_transform(X_train)
X_test = enc.transform(X_test)

In [38]:
X_train

array([[2., 3.],
       [0., 2.],
       [2., 1.],
       ...,
       [1., 6.],
       [1., 6.],
       [0., 0.]])

In [39]:
X_test

array([[4., 3.],
       [3., 3.],
       [0., 2.],
       ...,
       [0., 0.],
       [3., 1.],
       [2., 1.]])

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)
y_train, y_test

(array([5, 5, 6, ..., 7, 6, 3]), array([2, 7, 5, ..., 2, 5, 0]))

In [41]:
le.classes_

array(['Flowering', 'Fruit/Grain/Bulb Formation', 'Germination',
       'Harvest', 'Maturation', 'Pollination', 'Seedling Stage',
       'Vegetative Growth / Root or Tuber Development'], dtype=object)

In [42]:
le.inverse_transform(np.array([0,1]))

array(['Flowering', 'Fruit/Grain/Bulb Formation'], dtype=object)

In [43]:
data = {'Feature1': [1.0, 2.0, np.nan, 4.0],
        'Feature2': [5.0, np.nan, np.nan, 8.0],
        'Feature3': [10.0, 11.0, 12.0, np.nan]}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)


Original DataFrame:
   Feature1  Feature2  Feature3
0       1.0       5.0      10.0
1       2.0       NaN      11.0
2       NaN       NaN      12.0
3       4.0       8.0       NaN


In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'mean')
df_imputed = imputer.fit_transform(df)
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)
df_imputed

Feature1  Feature2  Feature3
0  1.000000       5.0      10.0
1  2.000000       6.5      11.0
2  2.333333       6.5      12.0
3  4.000000       8.0      11.0